const express=require('express'),multer=require('multer'),path=require('path'),fs=require('fs'),{spawn}=require('child_process'),crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3000,ROOT=__dirname,UP=path.join(ROOT,'uploads'),OUT=path.join(ROOT,'outputs');[UP,OUT].forEach(d=>fs.mkdirSync(d,{recursive:true}));app.use(express.json());app.use(express.static(path.join(ROOT,'public')));
const upload=multer({dest:UP,limits:{fileSize:500*1024*1024,files:20}});
function run(c,a){return new Promise((ok,no)=>{let p=spawn(c,a),o='',e='';p.stdout.on('data',d=>o+=d);p.stderr.on('data',d=>e+=d);p.on('error',no);p.on('close',x=>x?no(Error(e||`exit ${x}`)):ok({o,e}))})}
app.get('/api/health',(q,s)=>s.json({ok:true,status:'online',service:'Palend Downloader',time:new Date().toISOString()}));
app.post('/api/download',async(q,s)=>{let{url,format='mp4'}=q.body||{};if(!url||!/^https?:\\/\\//i.test(url))return s.status(400).json({ok:false,error:'URL tidak valid.'});let id=crypto.randomBytes(8).toString('hex'),tpl=path.join(OUT,id+'.%(ext)s');try{let a=['--no-playlist','--restrict-filenames','--no-warnings','-o',tpl];format==='mp3'?a.push('-x','--audio-format','mp3','--audio-quality','0'):a.push('-f','bv*+ba/b','--merge-output-format','mp4');a.push(url);await run(process.env.YTDLP_BIN||'yt-dlp',a);let f=fs.readdirSync(OUT).find(x=>x.startsWith(id+'.'));if(!f)throw Error('File hasil tidak ditemukan');s.json({ok:true,filename:f,download:'/api/file/'+encodeURIComponent(f)})}catch(e){s.status(500).json({ok:false,error:'Gagal memproses. Pastikan yt-dlp dan FFmpeg tersedia serta URL didukung.',detail:e.message.slice(0,700)})}});
app.get('/api/file/:name',(q,s)=>{let f=path.join(OUT,path.basename(q.params.name));fs.existsSync(f)?s.download(f,path.basename(f)):s.status(404).send('File tidak ditemukan')});
app.post('/api/merge',upload.array('videos',20),async(q,s)=>{if(!q.files||q.files.length<2)return s.status(400).json({ok:false,error:'Pilih minimal 2 video.'});let id=crypto.randomBytes(8).toString('hex'),list=path.join(UP,id+'.txt'),out=path.join(OUT,id+'-palend.mp4');try{fs.writeFileSync(list,q.files.map(f=>`file '${f.path.replace(/'/g,"'\\''")}'`).join('\n'));await run(process.env.FFMPEG_BIN||'ffmpeg',['-y','-f','concat','-safe','0','-i',list,'-c','copy',out]);s.json({ok:true,filename:path.basename(out),download:'/api/file/'+encodeURIComponent(path.basename(out))})}catch(e){s.status(500).json({ok:false,error:'Penggabungan gagal. Coba video dengan codec/resolusi yang kompatibel.',detail:e.message.slice(0,700)})}finally{(q.files||[]).forEach(f=>{try{fs.unlinkSync(f.path)}catch{}});try{fs.unlinkSync(list)}catch{}}});
app.get('*',(q,s)=>s.sendFile(path.join(ROOT,'public','index.html')));app.listen(PORT,'0.0.0.0',()=>console.log('Palend Downloader listening on '+PORT));
